### ISSUE TITLE
Upgrades purchased

### ISSUE THREAD

**Issue by Fulji** [pie3636/fire-watcher#18]
Elles n'ont pas toutes une tooltip... (Pour le moment Forest Exploration, Twistrike et Bonfire, je ne les ais pas toute j'ai reset)

EDIT : En fait y'a que Campfire et Pyramid fire qui ont une tooltip...

**Comment by pie3636** [comment]
Toujours d'actualité?

**Comment by Fulji** [comment]
Là c'est bon. ^^

**Comment by pie3636** [comment]
Bon, je ferme, mais hésite pas à la réouvrir si tu as à nouveau le problème...
Fixed in 0.7.7
