### ISSUE TITLE
Titre excentré

### ISSUE THREAD

**Issue by Fulji** [pie3636/fire-watcher#22]
~~Comme mis sur fb : les logs sont collés sur le bord gauche c'est très moyen pour lire.~~
Mais il y a un autre problème graphique, le titre "Fire Watcher v0.7.6" avec la petite flamme sont plus à gauche que lorsque je suis sur les autres "onglets"...

Edit : The issue only appears whenever the scrollbar overlaps with the navbar (specifically on the Changelog tab).

~~[D'ailleurs le titre est cliquable alors qu'il ne fait rien...]~~

**Comment by pie3636** [comment]
Fixed as of latest version (which hasn't been pushed yet).
