### ISSUE TITLE
Fan the flames bloqué 

### ISSUE THREAD

**Issue by Fulji** [pie3636/fire-watcher#30]
sur "Increase the fire duration by 3 minutes 20.000 seconds. "
pourtant dans stat : "Flames fanning : 2.097 M" (bon ok ça se voit pas mais c'était à 2.096 M juste avant)

**Comment by pie3636** [comment]
Pas vraiment une erreur, plutôt un problème de compatibilité ascendante. Autrement dit, il suffisait de reset ta save.

Not an issue.
